### ISSUE TITLE
BTK Issue

### ISSUE THREAD

**Issue by ykukkim** [kidzik/event-detector#2]
All the dependencies do not get downloaded using your instruction, **matplotlib** and **sklearn** needs to be installed manually.

I am using Python 2.7 on Mac OS Catalina, and when I run the script this is the error I get

> ykk@Yongs-MBP Desktop % event-detector har20_0.c3d hello.c3d
Using TensorFlow backend.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/event-detector", line 10, in <module>
    from eventdetector.annotate import process
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/eventdetector/annotate.py", line 11, in <module>
    import btk
  File "/usr/local/lib/python2.7/dist-packages/btk/__init__.py", line 31, in <module>
    _btk = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/btk/__init__.py", line 27, in swig_import_helper
    _mod = imp.load_module('_btk', fp, pathname, description)
ImportError: dlopen(/usr/local/lib/python2.7/dist-packages/btk/_btk.so, 2): no suitable image found.  Did find:
	/usr/local/lib/python2.7/dist-packages/btk/_btk.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
	/usr/local/lib/python2.7/dist-packages/btk/_btk.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03

I have downloaded btk as **btk-0.3.0-1_x86_64.rpm** which I uninstall then put it to the corresponding directory as stated on the script. 

Could you have a look at this please?

Thank you,

**Comment by kidzik** [comment]
Thank you @ykuk0906 for reporting. What is the output if you simply try to install btk with their pypi package:
```bash
pip install btk
```

**Comment by ykukkim** [comment]
Thank you for your comment @kidzik .

This is the error I get when I run:
`pip install btk`

> ERROR: Could not find a version that satisfies the requirement btk (from versions: none)
ERROR: No matching distribution found for btk

My Python is 2.7.16 from `python --version`

**Comment by kidzik** [comment]
And what happens when you try to install from the egg?
You can download it from here https://pypi.org/project/btk/#files
and install with
```bash
python -m easy_install btk-0.3.0-py2.7_macosx-10.7-intel.egg 
```

**Comment by ykukkim** [comment]
`python -m easy_install btk-0.3.0-py2.7_macosx-10.7-intel.egg`

> WARNING: The easy_install command is deprecated and will be removed in a future version.
> Searching for btk-0.3.0-py2.7_macosx-10.7-intel.egg
> Reading https://pypi.org/simple/btk-0.3.0-py2.7_macosx-10.7-intel.egg/
> Reading https://pypi.org/simple/btk-0.3.0-py2.7-macosx-10.7-intel.egg/
> Couldn't find index page for 'btk-0.3.0-py2.7_macosx-10.7-intel.egg' (maybe misspelled?)
> Scanning index of all packages (this may take a while)
> Reading https://pypi.org/simple/
> No local packages or working download links found for btk-0.3.0-py2.7_macosx-10.7-intel.egg
> error: Could not find suitable distribution for Requirement.parse('btk-0.3.0-py2.7_macosx-10.7-intel.egg')
> 

This is the error I get..  I downloaded anacoonda2.7 to have a separate environment, and I tried first with 
`pip install btk` which gives me this:

> `ERROR: Could not find a version that satisfies the requirement btk (from versions: none)
ERROR: No matching distribution found for btk

then I downloaded the egg and used your comment.

**Comment by ykukkim** [comment]
I have managed to run it using Docker! but I would like to know where I can modify your source code as my model is slightly different from yours. is this possible?

**Comment by kidzik** [comment]
That's terrific! The training code is here https://github.com/kidzik/event-detector-train but I admit it's more messy than the inference code. Hopefully it helps!
