### ISSUE TITLE
BTK import issue

### ISSUE THREAD

**Issue by Tikitaka02** [kidzik/event-detector#4]
Hello,

I tried to import btk on python 3.7 on windows 10. pip install did not work. I could import it with conda forge created by someone else, but your code did not work with the btk. I installed executable btk from pypi website, but I got an error of python27.dll conflict. I changed the python version to python 2.7. Then, it seems that tensorflow does not support python 2.7... I am sorry, but I do not know what to do from here...

I appreciate your solution in advance!

**Comment by kidzik** [comment]
Hi unfortunately BTK is discontinued and it's hard to make old versions work. In this project it's only used for processing c3d files, so you can try some other library like this one https://github.com/EmbodiedCognition/py-c3d (I haven't tested it though).

**Comment by Tikitaka02** [comment]
> Hi unfortunately BTK is discontinued and it's hard to make old versions work. In this project it's only used for processing c3d files, so you can try some other library like this one https://github.com/EmbodiedCognition/py-c3d (I haven't tested it though).

Frist of all, thank you so much for your reply and sorry for this late reply. I tried the github you mentioned, but it seems that the github is not capable for all types of c3d file. I had a specific data for testing (From humaneva dataset), so it did not work. I installed OpenSim, but I did not know how to extract data from TimeSeriesTableVec3 data type (I am guessing it is from C++) in Python. It seems that the OpenSim focuses more on C++ and Matlab supports. Finally, I tried ezc3d github (https://github.com/pyomeca/ezc3d#python-3) and could extract data in ndarray. It has the data dimension of [XYZ1] [Markers] [Frames]. How should I shape the data to use your model?

**Comment by kidzik** [comment]
It might not be the fairest answer, but I think at this point the easiest way to work with your own c3d files would be to adapt our data loader to your format using the library you use
https://github.com/kidzik/event-detector-train/blob/master/read.py#L17-L130
and then run the scripts normally. I haven't tried using OpenSim, however, it has python wrappers too.

**Comment by Tikitaka02** [comment]
I actually adapted it and could get predicted events, but I was not sure about its accuracy. Therefore, I wanted to check what the input data looks like. So, the curves should be a matrix of a number of frames * 99 variables. The 99 variables comes from 30 kinematics and 69 trajectories. The order is 15 left kinematics -> 15 right kinematics -> 15 left markers -> 15 right markers -> 15 left marker vel -> 15 right marker vel -> 9 midASI varriables. Then, in the process function, idxL samples 0, 2, 4, 6... 58th columns, and idxR samples 3, 5, 7, 9...61th columns from the curves. Is it correct?

**Comment by kidzik** [comment]
Yes, unfortunately, the code is very convoluted, but your interpretation is correct. Apologies for a very late response.

**Comment by Tikitaka02** [comment]
Thank you very much for your answer. I was just not sure the input because I do not know how btk works. I worked around, and it seems working alternatively to the btk. Could I do a pull request if you have time to check what I did ?

**Comment by kidzik** [comment]
Yes, that would be very helpful since we had a few people asking for a solution, thank you!

**Comment by Tikitaka02** [comment]
I have just done the pull request

**Comment by kidzik** [comment]
Thanks!
